In [3]:
import numpy as np
import math

def backward_difference_table(x, y):
    n = len(x)
    diff = np.zeros((n, n))
    
    diff[:, 0] = y
    
    for j in range(1, n):
        for i in range(n-1, j-1, -1):
            diff[i][j] = diff[i][j-1] - diff[i-1][j-1]
    
    return diff


def newton_backward(x, y, value):
    n = len(x)
    diff = backward_difference_table(x, y)
    
    h = x[1] - x[0]
    u = (value - x[n-1]) / h
    
    result = y[n-1]
    u_term = 1
    
    for i in range(1, n):
        u_term *= (u + i - 1)
        result += (u_term * diff[n-1][i]) / math.factorial(i)
    
    return result


x = [0, 1, 2, 3, 4]
y = [1, 2, 4, 8, 16]

value = 3.5

result = newton_backward(x, y, value)

print("Backward Difference Table:")
print(backward_difference_table(x, y))

print("\nInterpolated value at", value, "=", result)

Backward Difference Table:
[[ 1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.]
 [ 4.  2.  1.  0.  0.]
 [ 8.  4.  2.  1.  0.]
 [16.  8.  4.  2.  1.]]

Interpolated value at 3.5 = 11.3359375
